"""Initial migration

Revision ID: 3ee9445eb664
Revises: 
Create Date: 2025-11-21 21:58:34.473586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ee9445eb664'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=True),
    sa.Column('event_action', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.String(length=100), nullable=True),
    sa.Column('session_id', sa.String(length=100), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_table('feature_engineering',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_features', sa.JSON(), nullable=True),
    sa.Column('engineered_features', sa.JSON(), nullable=True),
    sa.Column('new_features', sa.JSON(), nullable=True),
    sa.Column('data_quality_score', sa.Float(), nullable=True),
    sa.Column('analysis_results', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('processing_time_ms', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feature_engineering_id'), 'feature_engineering', ['id'], unique=False)
    op.create_table('loan_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_age', sa.Integer(), nullable=True),
    sa.Column('person_income', sa.Float(), nullable=True),
    sa.Column('person_emp_length', sa.Integer(), nullable=True),
    sa.Column('home_ownership', sa.String(length=50), nullable=True),
    sa.Column('loan_amnt', sa.Float(), nullable=True),
    sa.Column('loan_int_rate', sa.Float(), nullable=True),
    sa.Column('loan_percent_income', sa.Float(), nullable=True),
    sa.Column('loan_intent', sa.String(length=50), nullable=True),
    sa.Column('loan_grade', sa.String(length=10), nullable=True),
    sa.Column('cb_person_cred_hist_length', sa.Integer(), nullable=True),
    sa.Column('default_on_file', sa.String(length=1), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('application_status', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loan_applications_id'), 'loan_applications', ['id'], unique=False)
    op.create_table('mitigation_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prediction_id', sa.Integer(), nullable=True),
    sa.Column('risk_level', sa.String(length=50), nullable=True),
    sa.Column('probability_default', sa.Float(), nullable=True),
    sa.Column('overall_strategy', sa.Text(), nullable=True),
    sa.Column('immediate_actions', sa.JSON(), nullable=True),
    sa.Column('short_term_goals', sa.JSON(), nullable=True),
    sa.Column('long_term_improvements', sa.JSON(), nullable=True),
    sa.Column('alternative_options', sa.JSON(), nullable=True),
    sa.Column('estimated_risk_reduction', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('implemented', sa.Boolean(), nullable=True),
    sa.Column('implementation_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('effectiveness_score', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mitigation_plans_id'), 'mitigation_plans', ['id'], unique=False)
    op.create_table('model_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_type', sa.String(length=50), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('precision', sa.Float(), nullable=True),
    sa.Column('recall', sa.Float(), nullable=True),
    sa.Column('f1_score', sa.Float(), nullable=True),
    sa.Column('auc_roc', sa.Float(), nullable=True),
    sa.Column('total_predictions', sa.Integer(), nullable=True),
    sa.Column('correct_predictions', sa.Integer(), nullable=True),
    sa.Column('false_positives', sa.Integer(), nullable=True),
    sa.Column('false_negatives', sa.Integer(), nullable=True),
    sa.Column('evaluation_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_metrics_id'), 'model_metrics', ['id'], unique=False)
    op.create_table('predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=True),
    sa.Column('input_features', sa.JSON(), nullable=True),
    sa.Column('risk_level', sa.String(length=50), nullable=True),
    sa.Column('probability_default', sa.Float(), nullable=True),
    sa.Column('binary_prediction', sa.Integer(), nullable=True),
    sa.Column('model_type', sa.String(length=50), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('shap_values', sa.JSON(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('key_factors', sa.JSON(), nullable=True),
    sa.Column('remediation_suggestion', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('prediction_time_ms', sa.Float(), nullable=True),
    sa.Column('actual_outcome', sa.Integer(), nullable=True),
    sa.Column('feedback_date', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_predictions_id'), 'predictions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_predictions_id'), table_name='predictions')
    op.drop_table('predictions')
    op.drop_index(op.f('ix_model_metrics_id'), table_name='model_metrics')
    op.drop_table('model_metrics')
    op.drop_index(op.f('ix_mitigation_plans_id'), table_name='mitigation_plans')
    op.drop_table('mitigation_plans')
    op.drop_index(op.f('ix_loan_applications_id'), table_name='loan_applications')
    op.drop_table('loan_applications')
    op.drop_index(op.f('ix_feature_engineering_id'), table_name='feature_engineering')
    op.drop_table('feature_engineering')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
